export default [
  {
    "s/n": 1,
    application_id: "QLN0000039",
    full_name: "Joseph Emerson",
    loan_amount: "5,000,000",
    status: "Approved",
    disbursed: "Pending",
    repayment: "Pending",
    application_date: "08 Apr, 2023 09: 17am",
    actions: "...",
  },
  {
    "s/n": 2,
    application_id: "QLN0000039",
    full_name: "Nureni Jamiu",
    loan_amount: "2,000,000",
    status: "Approved",
    disbursed: "Pending",
    repayment: "Pending",
    application_date: "08 Apr, 2023 09: 17am",
    actions: "...",
  },
  {
    "s/n": 3,
    application_id: "QLN0000039",
    full_name: "Anastasia Buryak",
    loan_amount: "6,000,000",
    status: "Approved",
    disbursed: "Pending",
    repayment: "Pending",
    application_date: "08 Apr, 2023 09: 17am",
    actions: "...",
  },
  {
    "s/n": 4,
    application_id: "QLN0000039",
    full_name: "Daniela K.",
    loan_amount: "4,000,000",
    status: "Approved",
    disbursed: "Pending",
    repayment: "Pending",
    application_date: "08 Apr, 2023 09: 17am",
    actions: "...",
  },
  {
    "s/n": 5,
    application_id: "QLN0000039",
    full_name: "Carexo Wood",
    loan_amount: "1,000,000",
    status: "Approved",
    disbursed: "Pending",
    repayment: "Pending",
    application_date: "08 Apr, 2023 09: 17am",
    actions: "...",
  },
];
